nav:
    - 首页: index.md
    - OpenGL:
        - 渲染管线: OpenGL/Pipeline.md
        - VAO、VBO、EBO: OpenGL/VAO_VBO_EBO.md
        - 光照: OpenGL/光照.md
        - 法线贴图: OpenGL/法线贴图.md
        - 材质: OpenGL/材质.md
        - 光源: OpenGL/光源.md
        - 几何着色器: OpenGL/几何着色器.md
        - 高级GLSL: OpenGL/高级GLSL.md
    - UE4:
        - 部署iOS打包环境: UE4/部署iOS打包环境.md
        - 生成xcode工程文件: UE4/生成xcode工程文件.md
    - 小记:
        - AppleWWDRCA证书: Note/AppleWWDRCA证书.md
        - Mac安装Homebrew: Note/Mac安装Homebrew.md
        - Mac卸载JDK: Note/Mac卸载JDK.md
    - markdown语法: markdown.md

site_name: 梦之斋
site_description: '梦之斋'
site_favicon: theme/favicon.ico
site_avatar: theme/avatar.png

site_url: https://hohooho.github.io/
repo_url: https://github.com/HoHooHo/HoHooHo.github.io
edit_uri: ""




theme:
    name: slate
    locale: zh
    custom_dir: custom_theme/

markdown_extensions:
    - mdx_math
    - admonition
    - toc:
        permalink: '#'

extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML'

plugins:
    - search
    
extra_css:
    - css/markdown-it-admonition.css
    - css/style.css
