nav:
    - Home: index.md
    - markdown: markdown.md
    - OpenGL:
        - VAO、VBO、EBO: OpenGL/VAO_VBO_EBO.md
        - 光照: OpenGL/光照.md
        - 材质: OpenGL/材质.md
        - 光源: OpenGL/光源.md
    - UE4:
        - test: UE4/test.md

site_name: 梦之斋
site_description: '梦之斋'
site_favicon: theme/favicon.ico
site_avatar: theme/avatar.png

site_url: https://hohooho.github.io/
repo_url: https://github.com/HoHooHo/HoHooHo.github.io
edit_uri: ""




theme:
    name: slate
    custom_dir: custom_theme/

markdown_extensions:
    - toc:
        permalink: '#'
    - markdown_katex:
        no_inline_svg: True
        insert_fonts_css: True
    - admonition

plugins:
    - search
    
extra_css:
    - css/markdown-it-admonition.css
    - css/style.css
