nav:
    - Home: index.md
    - OpenGL:
        - test: OpenGL/test.md
    - UE4:
        - test: UE4/test.md

site_name: 梦之斋
site_description: '梦之斋'

site_url: https://hohooho.github.io/
repo_url: https://github.com/HoHooHo/HoHooHo.github.io
edit_uri: ""

theme:
    name: slate

markdown_extensions:
    - toc:
        permalink: '#'
    - markdown_katex:
        no_inline_svg: True
        insert_fonts_css: True

plugins:
    - search
